# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DNNFOH4Xj4pZdUiITZ-oelv_mT4GMARx
"""

def pitagoras(a, b):
''''''
calcula a raiz quadrada

#(X - 2)*

print(1+2)

def estima_pi(n):
  den = list(range(1,2*n, 2))

list(range(1,10,2))

[(-1)**x for x in range(n)]

import numpy
numpy.pi

"""implate uma funçao que receba o valor de n inteiro e imprima ate a n-esima linha da seguinte forma
1
2 2
3 3 3
: : :
n n n n n n n n
"""

def imprimir_padrao(n):
    for i in range(1, n + 1):
        linha = ' '.join([str(i)] * i)
        print(linha)

# Exemplo de uso:
imprimir_padrao(5)

"""implate uma funçao que receba o valor de n inteiro e imprima ate a n-esima linha da seguinte forma
1
1 2
1 2 3
: : :
1 2 3 ... n
"""

def imprimir_padrao(n):
    for i in range(1, n + 1):
        linha = ' '.join([str(j) for j in range(1, i + 1)])
        print(linha)

# Exemplo de uso:
imprimir_padrao(5)